"""add role column to users

Revision ID: 67c7d9ec1b42
Revises: 0005c1ce95f1
Create Date: 2026-08-11 15:40:51.726198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67c7d9ec1b42'
down_revision: Union[str, Sequence[str], None] = '0005c1ce95f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_token_id'), table_name='blacklisted_token')
    op.drop_index(op.f('ix_blacklisted_token_token'), table_name='blacklisted_token')
    op.drop_table('blacklisted_token')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('blacklisted_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blacklisted_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('blacklisted_token_pkey'))
    )
    op.create_index(op.f('ix_blacklisted_token_token'), 'blacklisted_token', ['token'], unique=True)
    op.create_index(op.f('ix_blacklisted_token_id'), 'blacklisted_token', ['id'], unique=False)
    # ### end Alembic commands ###
