"""recreate apikeys_v2 properly

Revision ID: 28f2dbc6c151
Revises: 8144db61b9ea
Create Date: 2026-08-06 20:10:39.664633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28f2dbc6c151'
down_revision: Union[str, Sequence[str], None] = '8144db61b9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('request_today', sa.Integer(), nullable=True),
    sa.Column('last_request', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikeys_v2_id'), 'apikeys_v2', ['id'], unique=False)
    op.create_index(op.f('ix_apikeys_v2_key'), 'apikeys_v2', ['key'], unique=True)
    op.execute('DROP TABLE IF EXISTS blacklisted_token CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blacklisted_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('blacklisted_token_pkey'))
    )
    op.create_index(op.f('ix_blacklisted_token_token'), 'blacklisted_token', ['token'], unique=True)
    op.create_index(op.f('ix_blacklisted_token_id'), 'blacklisted_token', ['id'], unique=False)
    op.drop_index(op.f('ix_apikeys_v2_key'), table_name='apikeys_v2')
    op.drop_index(op.f('ix_apikeys_v2_id'), table_name='apikeys_v2')
    op.drop_table('apikeys_v2')
    # ### end Alembic commands ###
