from argon2 import PasswordHasher
from argon2.exceptions import VerificationError
from datetime import datetime, timedelta, timezone
import hashlib
import hmac
from app.core.config import settings
import jwt
ph=PasswordHasher()


def fingerprint_secret(value: str) -> str:
    """Return a deterministic, peppered fingerprint for a secret value.

    This is intended for high-entropy values generated by the server (JWTs and
    API keys), not user passwords.  It keeps raw credentials out of the DB
    while still allowing indexed lookups.
    """
    return hmac.new(
        settings.SECRET_KEY.encode("utf-8"),
        value.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

def hashed_password(password: str) -> str:
    return ph.hash(password)
def verify_password(password:str,hashed_password:str) ->bool:
    try:
        return ph.verify(hashed_password,password)
    except VerificationError:
        return False
def create_access_token(data:dict)->str:
    to_encode=data.copy()
    expire=datetime.now(timezone.utc) + timedelta(
        minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES
    )
    to_encode.update({
        "exp":expire,
        "type":"access"
    })
    encode_jwt=jwt.encode(
        to_encode,
        settings.SECRET_KEY,
        algorithm=settings.ALGORITHM
    )
    return encode_jwt

def create_refresh_token(data:dict)->str:
    to_encode=data.copy()
    expire=datetime.now(timezone.utc) + timedelta(
        days=settings.REFRESH_TOKEN_EXPIRE_DAYS
    )
    to_encode.update({
        "exp":expire,
        "type":"refresh"
    })
    encode_jwt=jwt.encode(
        to_encode,
        settings.SECRET_KEY,
        algorithm=settings.ALGORITHM

    )
    return encode_jwt
def create_password_reset_token(
    email: str,
    reset_version: int
) -> str:
    expire = datetime.now(timezone.utc) + timedelta(minutes=30)

    return jwt.encode(
        {
            "sub": email,
            "purpose": "reset_password",
            "type": "password_reset",
            "reset_version": reset_version,
            "exp": expire
        },
        settings.SECRET_KEY,
        algorithm=settings.ALGORITHM
    )
